// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCirPqGinNmuN8RxDTGhoGAEEpc4TBvgkI',
    appId: '1:204380842788:android:9bbc0da626063cbf0061b1',
    messagingSenderId: '204380842788',
    projectId: 'kalyan777-56ed1',
    storageBucket: 'kalyan777-56ed1.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRZiJFYLu4BZdISN1VupMzTkeBn_srKD0',
    appId: '1:204380842788:web:bbf9b0a0bf33e9de0061b1',
    messagingSenderId: '204380842788',
    projectId: 'kalyan777-56ed1',
    authDomain: 'kalyan777-56ed1.firebaseapp.com',
    storageBucket: 'kalyan777-56ed1.firebasestorage.app',
    measurementId: 'G-PBLVCX6ZDF',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqjCZvso-OmcaIu2EjCuygxOFbfbfv9FA',
    appId: '1:204380842788:ios:e13db9fb6578bfb40061b1',
    messagingSenderId: '204380842788',
    projectId: 'kalyan777-56ed1',
    storageBucket: 'kalyan777-56ed1.firebasestorage.app',
    iosBundleId: 'com.kalyan.weview',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqjCZvso-OmcaIu2EjCuygxOFbfbfv9FA',
    appId: '1:204380842788:ios:e13db9fb6578bfb40061b1',
    messagingSenderId: '204380842788',
    projectId: 'kalyan777-56ed1',
    storageBucket: 'kalyan777-56ed1.firebasestorage.app',
    iosBundleId: 'com.kalyan.weview',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRZiJFYLu4BZdISN1VupMzTkeBn_srKD0',
    appId: '1:204380842788:web:f962dfe13c65bd010061b1',
    messagingSenderId: '204380842788',
    projectId: 'kalyan777-56ed1',
    authDomain: 'kalyan777-56ed1.firebaseapp.com',
    storageBucket: 'kalyan777-56ed1.firebasestorage.app',
    measurementId: 'G-7TK2L44MMQ',
  );

}